name = "introscicomp"
uuid = "9cc4ad9d-5c8e-4864-9e39-577ccf2bdce2"
authors = ["sezerh24 <34803300+sezerh24@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
